config/routes.rb
Rails.application.routes.draw do
 
  
  root 'sessions#index'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'
  get '/signup' => 'users#new'
  post '/signup' => 'users#create'
  get '/auth/google_oauth2/callback' => 'sessions#omniauth'
  get 'events/number_of_located_events' => 'events#number_of_located_events'
  
  resources :activities do
    resources :events, only: [:index, :new, :create]
  end
  #see if events should be a stand alone or always be nested under locations.
  resources :events
  resources :locations do
    resources :events
  end
  resources :users
  # resources :categories, only: [:new, :create, :show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ApplicationRecord
    belongs_to :location
    belongs_to :activity
    
    validates :name, :date, presence: true
    #activity/location won't save unless event is valid 
    validates_associated :activity, :location
   
   
    scope :number_of_located_events, -> {joins(:location).count}

    
    #bringing in params from activity (the aactivityform withtin events)
    def activity_attributes=(activity_params)
      activity = Activity.find_or_create_by(activity_params)
      # make sure if valid, then set that activity, if not then set the one that exists
      # @activity.valid? ? self.activity = activity : self.activity
      # didn't fill out params
      activity_params[:name].empty? ? self.activity : self.activity = activity 
    end 
    
    
    def datetime
        self.date.strftime("%A, %b %d") if self.date
    end

    def nested_activity_find_nested_resource
      params[:activity_id] && @activity = Activity.find_by_id(params[:activity_id])
    end







end

app/controllers/events_controller.rb
class EventsController < ApplicationController

    def number_of_located_events
        @events = Event.all
    end

    def show
        @event = Event.find(params[:id])
        respond_to do |f|
            f.html {render :show}
            f.json { render json: @event}
        end
    end

    def index
        
        #check if nested                     #find nested resource
        if  params[:activity_id] && @activity = Activity.find_by_id(params[:activity_id])
            @events = @activity.events
             
        elsif params[:location_id] && @location = Location.find_by_id(params[:location_id])   
            @events = @location.events
        else
        @events = current_user.events
        # @events = Event.all
        end
        respond_to do |f|
            f.html {render :index}
            f.json { render json: @events}
        end
    end

    def new
      if  params[:activity_id] && @activity = Activity.find_by_id(params[:activity_id])
        @event = @activity.events.build
      else
        @event = Event.new
        @event.build_activity
      end
    end

    def create
        if  params[:activity_id] && @activity = Activity.find_by_id(params[:activity_id])
            @event = @activity.events.build(event_params)
        else
           @event = Event.new(event_params)
        end
        
        if @event.save
            respond_to do |f|
            f.html {redirect_to event_path(@event)}
            f.json {render json: @event}
            end
        else
            render :new
        end
    end

    def edit
        @event = Event.find_by(id: params[:id])
        respond_to do |f|
            f.html {render :edit}
            f.json { render json: @event}
        end
    end
    
    def update
        @event = Event.find_by(id: params[:id])
        if @event.update(event_params)
            redirect_to event_path(@event)
        else
            render :edit
        end
    end
   
    private 
    def event_params
      params.require(:event).permit(:name, :date, :location_id, :activity_id, :activity_attributes => [:name, :description, :duration, :user_id])
    end

    
end

app/helpers/events_helper.rb
module EventsHelper

   def display_index_header
      
     if @activity  
      content_tag(:h2, "Events with #{@activity.name}")
     elsif @location
      content_tag(:h2, "Events at #{@location.name}")
     else
       content_tag(:h1, "All Events")
     end
   end

   def display_date(t)
    "on #{t.datetime}" if t.date
  end


    def activity_form_option(form_builder)
        if @activity
           content_tag(:p, "Activity: #{@activity.name}")
        else
           render partial: "activityform", locals: {f: form_builder}
        end
      end


end

app/views/events/_activityform.html.erb
<br><%= f.label :activity_id, "Select an existing activity:"%>
<%=f.collection_select :activity_id, current_user.activities, :id, :name, include_blank: true %>
                      
<h3>Or Create a new Activity:</h3>
    
  <%= f.fields_for :activity do |a| %>
    <%= a.label :name %>
    <%= a.text_field :name %>
    <br></br>

  <%= a.label :duration %>
  <%= a.number_field :duration %>
  <br></br>

  <%= a.label :description %>
  <%= a.text_field :description %>
    <br></br>
     <%# associating a user %>
  <%= a.hidden_field :user_id, value: current_user.id %>
    <br></br>

  <% end %>

app/views/events/_form.html.erb

<%# posting to a nested route %>
<%= form_for [@activity, @event] do |f|%>
<%=f.label :name%>
<%=f.text_field :name%><br>

<%=f.label :date%>
<%=f.date_field :date%><br>

<%=f.label :location_id%>
<%=f.collection_select :location_id, current_user.locations, :id, :name %><br>

<%=activity_form_option(f)%> 


<%=f.submit%>

<%end%>

app/views/events/edit.html.erb
<h1>Edit <%= @event.name %></h1>
<h3><%= render partial: "layouts/errors", locals: { object: @event } %></h3>
<%= render "form" %>

app/views/events/index.html.erb
<%= display_index_header%>

<ul>
<% @events.order(:date).each do |event| %>
<li> <%=link_to event.name.titleize, event_path(event) %><br>
      <button id='event-data-<%=event.id%>'>SEE EVENT</button>
      <div id='ajax-event-<%= event.id %>'></div>
    <%# <%=display_date(event)%> 
    <%# <%=event.location.name.titleize%> <br><br>
    </li>
    <%end%>
<br>



 
<br>
<br>

<%= link_to "Number of Located Events", events_number_of_located_events_path%>

app/views/events/new.html.erb
<h1>New Event</h1>

<h3><%= render partial: "layouts/errors", locals: { object: @event } %></h3>

<%= form_for [@activity, @event] do |f|%>
<%=f.label :name%>
<%=f.text_field :name%><br>

<%=f.label :date%>
<%=f.date_field :date%><br>

<%=f.label :location_id%>
<%=f.collection_select :location_id, current_user.locations, :id, :name %><br>

<%=activity_form_option(f)%> 


<%=f.submit%>

<%end%>


app/views/events/number_of_located_events.html.erb
<h1>NUMBER OF YOUR EVENTS WHICH HAVE A LOCATION:</h1>
<br>
<h1><%=current_user.events.number_of_located_events%></h1>

app/views/events/show.html.erb

<h3>Event: <%=@event.name.titleize%></h3>
<br>
<h3>Date: <%=display_date(@event)%></h3>
<br>
<h3>Location: <%=link_to @event.location.name.titleize, location_events_path(@event.location)%></h3>
<br>
<h3>Activity: <%=link_to @event.activity.name.titleize, activity_events_path(@event.activity)%></h3>

<h5> <%= link_to "Edit Event", edit_event_path(@event)%> </h5>

<%# <button id='events-index'>SEE ALL EVENTS</button>
<div id='ajax-events-index'>[placeholder for all events]</div> %>