config/routes.rb
Rails.application.routes.draw do
 
  
  root 'sessions#index'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'
  get '/signup' => 'users#new'
  post '/signup' => 'users#create'
  get '/auth/google_oauth2/callback' => 'sessions#omniauth'
  get 'events/number_of_located_events' => 'events#number_of_located_events'
  
  resources :activities do
    resources :events, only: [:index, :new, :create]
  end
  #see if events should be a stand alone or always be nested under locations.
  resources :events
  resources :locations do
    resources :events
  end
  resources :users
  # resources :categories, only: [:new, :create, :show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/activity.rb
class Activity < ApplicationRecord
  has_many :events
  has_many :locations, through: :events
  belongs_to :user
  # belongs_to :category

  validates :name, :description, :duration, presence: :true
  validates_uniqueness_of :name, scope: :user_id 
 

  scope :order_by_longest_duration, -> { order(duration: :desc) }
  scope :duration_search, -> (search_duration){ where("duration > ?", search_duration)}




end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
before_action :set_activity, only: [:show]
    
  def index
    @activity = Activity.new
    @activities = current_user.activities.order_by_longest_duration
    respond_to do |f|
      f.html {render :index}
      f.json {render json: @activities}
    end
  end

  def show
    
  end

  def new
    @activity = Activity.new
    render :new, layout: false
  end

  def create 
    # raise params.inspect
    @activity = current_user.activities.build(activity_params)
    if @activity.save
      render json: @activity, status: 201
      # respond_to do |f|
      # f.json {render json: @activity}
      # f.html {redirect_to activity_path(@activity)}
      # end
    else
        render :new
    end
  end

  def edit
    @activity = Activity.find_by(id: params[:id])
    respond_to do |f|
      f.html {render :edit}
      f.json {render json: @activity}
    end
  end

  def update
    @activity = Activity.find_by(id: params[:id])
    if @activity.update(activity_params)
        redirect_to activity_path(@activity)
    else
        render :edit
    end
  end

  def destroy
    @activity.destroy
    redirect_to activities_path
  end

  private

  def activity_params
    params.require(:activity).permit(:name, :description, :duration)
  end

  def set_activity
    @activity = Activity.find_by(id: params[:id])
    redirect_to activities_path if !@activity
  end







end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/_form.html.erb
<style> 
    body {
      background-color: lightyellow; 
    }

    form {
      /* display: flex; */
      justify-content: center;
      /* align-items: center; */
    }
  </style>


<%= form_for @activity, html: {id: :myForm } do |f|%>
<%=f.label :name%>
<%=f.text_field :name, required:true %><br />
<br>
<%=f.label :duration, "Duration in Minutes"%>
<%=f.number_field :duration, required:true%><br />
<br>
<%=f.label :description%>
<%=f.text_field :description, required:true%>
<br>
<%=f.submit%>
<br>
<%end%>
 
      <script>
       $(function() {
        $("form#myForm.new_activity").on("submit", function(event) {
          event.preventDefault()
          var post_url = $(this).attr("action");
          var request_method = $(this).attr("method");
          var form_data = $(this).serialize();

          $.ajax({
              url: post_url,
              type: request_method,
              data: form_data
          }).done(function(response){
               var activity = new Activity(response);
               const newHtml = activity.newActivityHTML();
              $("#insert-activity").append(newHtml);
              $('#activty-form-placeholder').html('')
              $("#activity-form-button").show();
          }).error((response) => {
             let errorMessage = "There was an error."
             $('#activty-form-placeholder').html(errorMessage)
          });
        });
      });


class Activity {
  constructor(obj) {
    this.id = obj.id
    this.name = obj.name,
    this.description = obj.description
    this.duration = obj.duration 
  }
}

Activity.prototype.newActivityHTML = function () {
  return (`
  <div class='activity'>
  <ul>
  <li> <strong> <a href="activities/${this.id}">${this.name}</a></strong> 
  ${this.duration} Minutes<br>
  ${this.description}</li>
  </ul>
  </div>
  `)
}
     </script>



      <%# src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js" %>

app/views/activities/edit.html.erb
<h1>Edit <%= @activity.name %></h1>

<%= render "form" %>

app/views/activities/index.html.erb
<h1>Activities</h1>

<button id="activity-form-button">New Activity</button>


<div id="activty-form-placeholder"></div>

<br>
<br>
<br>

<div id="insert-activity"></div>
<ul>
 <% @activities.each do |activity|%>
<li><strong><%=link_to activity.name.titleize, activity_path(activity)%></strong>
<%=activity.duration%> Minutes<br>
<%=activity.description%>
<%=link_to "See All Events With This Activity", activity_events_path(activity)%> | <br>
<%= link_to "Add This Activity To A New Event", new_activity_event_path(activity) %>
</li>
<br><br>
<%end%>
</ul>
<br>
<div id="activity_div"> 
   <h2 id="activityName"></h2>
  <p id="activityDuration"></p>
  <p id="activityDescription"></p>
</div>

<%# <form id="myForm1" action="activities" method="post"> 

    <%# <%= render "form" %>
    <%# <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
    <%# Name: <input type="text" name="activity[name]" /> 
    <br>
    Duration <input type="number" name="activity[duration]">
    <br>
    Description: <br><textarea name="activity[description]"></textarea>} 
    <input type="submit" value="Submit Activity" /> 
    </form> %> 



    
     


    <br>
    <br>
    <br>
    <br>

app/views/activities/new.html.erb
<h2>New Activity Form:</h2>
<h3><%= render partial: "layouts/errors", locals: { object: @activity } %></h3>
<%= render "form" %>

app/views/activities/show.html.erb
<h1><%= @activity.name.titleize %></h1>
<h2> <%= @activity.duration%> Minutes<h2>
 <%=@activity.description%>
<br><br>
<h5> <%= link_to "Edit Activity", edit_activity_path(@activity)%> </h5>
  <%# <%= link_to 'Delete Activity', @activity,  method: :delete, data: { confirm: 'Are you sure?' } %>

  