config/routes.rb
Rails.application.routes.draw do
 
  
  root 'sessions#index'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'
  get '/signup' => 'users#new'
  post '/signup' => 'users#create'
  get '/auth/google_oauth2/callback' => 'sessions#omniauth'
  get 'events/number_of_located_events' => 'events#number_of_located_events'
  
  resources :activities do
    resources :events, only: [:index, :new, :create]
  end
  #see if events should be a stand alone or always be nested under locations.
  resources :events
  resources :locations do
    resources :events
  end
  resources :users
  # resources :categories, only: [:new, :create, :show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/location.rb
class Location < ApplicationRecord
  belongs_to :user
  has_many :events
  has_many :activities, through: :events

  validates :name, :address, presence: :true
  validates_uniqueness_of :name, :address, scope: :user_id 
 
  scope :order_reverse, -> {order(name: :desc).first(4)}

end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController

  def index
    @locations = current_user.locations
    respond_to do |f|
      f.html {render :index}
      f.json {render json: @locations}
    end
  end

  def show
    @location = Location.find_by(id: params[:id])
    respond_to do |f|
      f.html {render :show}
      f.json {render json: @location}
    end
  end

  def new
    @location = Location.new
    # render :new, layout: false
  end
  
  def create
    @location = current_user.locations.build(location_params)
    if @location.save
      # render json: @location
      respond_to do |f| 
        f.html {redirect_to locations_path} 
        f.json {render json: @location}
      end
    else
        render :new
    end
  end

  def edit
    @location = Location.find_by(id: params[:id])
    respond_to do |f|
      f.html {render :edit}
      f.json {render json: @location}
    end
  end

  def update
    @location = Location.find_by(id: params[:id])
    if @location.update(location_params)
      respond_to do |format| 
      format.html {redirect_to location_path(@location)}
      format.json { render json: @location}
      end
    else
        render :edit
    end
  end

  private

  def location_params
    params.require(:location).permit(:name, :address)
  end

end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/locations/_form.html.erb
<%= form_for @location, html: {id: :location_form } do |f| %>
  <%#wrap in fields with errors class %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>

  <%= f.label :address %>
  <%= f.text_field :address %>

  <%= f.submit%>

<% end %>






<%# 
// $(function() {
//         $("button#hello").on("click", function(event) {
//           event.preventDefault()
//           alert("hello")
//         })
// })
// const ready = (callback => {
//   if (document.readyState != "loading") callback();
//   else document.addEventListener("DOMContentLoaded", callback);
// })


// ready(() => {
//   // document.querySelector("form#location_form.new_location").addEventListener("submit", (e) => {
//       document.querySelector("button#hello").addEventListener("click", (e) => {
//       e.preventDefault()
//       alert("hello")

//   })
// })
   %>

app/views/locations/edit.html.erb
<h1>Edit <%= @location.name %></h1>

<%= render "form" %>

app/views/locations/index.html.erb
<h1>My Locations Page</h1>
<br>

<h3>Create A New Location:</h3>
<form id="super_location_form">
<%= hidden_field_tag :authenticity_token, form_authenticity_token %>
<label for="name">Name</label>
<input type='text' name = "location[name]" id="location_name">
<br>
<label for="address">Address</label>
<input type='text' name = "location[address]" id="location_address">
<button type='submit'>Submit</button>
</form>
<br>
<br>
<br>
  <%# <button id="new-location-button">New Location</button> %>

   <div id="location-form-placeholder"></div>
<div id=main>
<br>
<br>
<%# <h3>My Locations:</h3> %>
<ul>
<% @locations.each do |location|%>
 <li><h4><%= link_to location.name.titleize, location_path(location) %> </h4>
 <%=location.address.titleize%>
 <%end%></li>
 <ul>
</div>
<%# <div id='new-locations'>placeholder</div>
<br><br>
<button id='ajax-new-location'> NEW LOCATION </button>
<div id='new-location-form-div'> </div> %>
<%# <div id="new-locations">
<%= link_to 'New Location', new_location_path %>
<%# </div> %>
<br>
<br>
<h5>Press Button to See Locations Sorted:</h5>
<button id="location_sorter">Sort Locations</button>
<br>
<br>
 <div id="location-sort-placeholer"></div>
<br>
<br>

<script>

const locationForm = document.getElementById('super_location_form');

locationForm.addEventListener('submit', (e) => {
  e.preventDefault()
  
  const formData = new FormData(locationForm);

  fetch( "locations.json",{
    method: 'POST',
    body: formData
  }).then(function (response) {
    return response.json();
  }).then(function (text){
     const locationText = new Location(text)
     const newLocationText = locationText.newLocationHTML()
     const mainContainer = document.querySelector("#location-form-placeholder")
     const z = document.createElement('div');
     z.innerHTML = newLocationText;
     mainContainer.appendChild(z);
     document.querySelector("#super_location_form").reset()
  }).catch( function (error) {
    console.error(error);
  })

})


class Location {
  constructor(obj) {
    console.log(obj)
    this.id = obj.id
    this.name = obj.name,
    this.address = obj.address 
  }
}

Location.prototype.newLocationHTML = function () {
  return (`
  <div class='location'>
  <ul>
  <li> <strong> <h4> <a href="locations/${this.id}">${this.name}</a></h4></strong>
  <br>
  ${this.address}</li>
  </ul>
  </div>
  `)
}

const locationSorter = document.getElementById('location_sorter');
locationSorter.addEventListener('click', (e) => {
  const mainContainer = document.querySelector("#location-sort-placeholer")
  if (mainContainer.innerHTML === ""){
  locationSorting()
  } else {
    document.getElementById('location-sort-placeholer').innerHTML = ""
  }
})

function locationSorting() {
  $.ajax({
    url:"/locations",
    method: 'GET',
    dataType: 'json',
    success: function (data) {
      data.sort(function(a, b) {
        var nameA = a.name.toUpperCase(); // ignore upper and lowercase
        var nameB = b.name.toUpperCase(); // ignore upper and lowercase
        if (nameA < nameB) {
          return -1;
        }
        if (nameA > nameB) {
          return 1;
        }

        // names must be equal
        return 0;
      });
       const array = data.map( dat => 
       '<ul>' + '<li>' + dat.name + '</li>' + '</ul>' 
       )
        // console.log(array)
        for (const element of array) {
        const z = document.createElement('div')
        z.innerHTML = element;
        document.querySelector("#location-sort-placeholer").appendChild(z);
        }
    }
  })
}

</script>


app/views/locations/new.html.erb
<div id=js-location-info></div>
<h2>New Location Form:</h2>
<h3><%= render partial: "layouts/errors", locals: { object: @location } %></h3>
<%= render "form" %>
<%# <%= javascript_include_tag "/app/javascript/locationForm_channel.js" %>



app/views/locations/show.html.erb

<div id='location-div'>
<h1 class='location-name'><%= @location.name.titleize %></h1>

<h2 class='location-address'><%=@location.address.titleize%></h2>
<br><br>
<h5><%= link_to "Edit Location", edit_location_path(@location) %></h5>
</div>
<a href ="#" class="location-data" data-id="<%=@location.id%>">SEE NEXT LOCATION</a>


<%# <div id='random'>[place holder]  </div> %>