config/routes.rb
Rails.application.routes.draw do
 
  
  root 'sessions#index'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'
  get '/signup' => 'users#new'
  post '/signup' => 'users#create'
  get '/auth/google_oauth2/callback' => 'sessions#omniauth'
  get 'events/number_of_located_events' => 'events#number_of_located_events'
  
  resources :activities do
    resources :events, only: [:index, :new, :create]
  end
  #see if events should be a stand alone or always be nested under locations.
  resources :events
  resources :locations do
    resources :events
  end
  resources :users
  # resources :categories, only: [:new, :create, :show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_errors.html.erb
<%# try ignores the method if returns nil inorder not to throw error %>
<% if object.try(:errors).try(:any?) %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %> prohibited this from being saved:</h2>

    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ActivityPlanner</title>
    
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script src="http://malsup.github.com/jquery.form.js"></script> 
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
     <%# <%=javascript_include_tag "application", 'data-turbolinks-track': true %> 
  </head>

  <body>
      
      <% if logged_in? %>

    <nav class='navbar'>
      <%= link_to 'My Locations', locations_path%>
      <%# <%= link_to 'Add a Location', new_location_path %>
      <%# <%= link_to 'Add an Activity', new_activity_path%>
      <%= link_to 'My Activities', activities_path %>
      <%= link_to 'Add an Event', new_event_path %>
      <%= link_to 'My Events', events_path%>
      <%= link_to 'Logout', '/logout', method: :delete%>
    </nav>
    <% else %>
      <%= link_to 'Log In', login_path %>
    <% end %>
    <%flash.each do |k, v|%>
    <%=content_tag :div, v, class: "flash-#{k}"%>
    <%end%>
     <div class="container">
    <%= yield %>
    </div>
  </body>
</html>